export const Commoncontent = {

    // Sidenavbar
    SIDENAVBAR_WELCOME: "Welcome",
    SIDENAVBAR_HOME: "Home",
    SIDENAVBAR_ORGNIZATION: "Organization",
    SIDENAVBAR_ABOUT_US: "About us",
    SIDENAVBAR_COMPANY_POLICIES: "Company Policies",
    SIDENAVBAR_HR_POLICY: "HR Policy",
    SIDENAVBAR_HOLIDAY_LIST: "Holiday List",
    SIDENAVBAR_ORGNIZATION_TREE: "Organization Tree",
    SIDENAVBAR_EMPLOYEES: "Employees",
    SIDENAVBAR_EMPLOYEE_DIRECTORY: "Employee Directory",
    SIDENAVBAR_OPERATIONS: "Operations",
    SIDENAVBAR_ATTENDANCE: "Attendance",
    SIDENAVBAR_YEAR: "Year",
    SIDENAVBAR_MONTH: "Month",
    SIDENAVBAR_LEAVES: "Leaves",
    SIDENAVBAR_REQUEST: "Request",
    SIDENAVBAR_BALANCE: "Balance",
    SIDENAVBAR_PERFORMANCE: "Performance",
    SIDENAVBAR_APPRAISAL_SHEET: "Appraisal Sheet",
    SIDENAVBAR_TRACKING_SHEET: "Tracking Sheet",
    SIDENAVBAR_RECRUITMENT: "Recruitment",
    SIDENAVBAR_CANDIDATE: "Candidate",
    SIDENAVBAR_OPENINGS: "Openings",
    SIDENAVBAR_PAYROLL: "Payroll",
    SIDENAVBAR_SALARY: "Salary",
    SIDENAVBAR_PAYSLIP: "Payslip",
    SIDENAVBAR_TAX_CALCULATOR: "Tax Calculator",
    SIDENAVBAR_DATA_MANAGER: "Data Manager",
    SIDENAVBAR_DATA_MASTER: "Data Master",
    SIDENAVBAR_ASSETS: "Assets",
    SIDENAVBAR_DEPARMENT: "Department",
    SIDENAVBAR_DESIGNATION: "Designation",
    SIDENAVBAR_DATA_MAPPING: "Data Mapping",
    SIDENAVBAR_ASSETS_EMPLOYEE: "Assets Employee",
    SIDENAVBAR_LOGOUT: "Logout",

    //LOGIN
    HR_LOGIN: "HR Login",
    login_USERNAME: "Username",
    LOGIN_PASSWORD: "Password",
    LOGIN_FORGOT_PASSWORD: "forgot password?",
    LOGIN: "Login",

    // Common Veriable use in add Component
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    ERROR_MESSAGE: "This field is required",
    SEARCH: "Search...",
    BTN_SAVE: "Save",
    BTN_UPDATE: "Update",
    BTN_CLOSE: "Close",
    DELETE_MESSAGE_POPUP: "Are your sure you want to delete?",
    BTN_DELETE: "Delete",

    // Assets
    ASSETS_TITLE: "Assets",
    ASSETS_EXCEL_ACTION: "Excel Action",
    ASSETS_DOWNLOAD_DATA: "Download Data",
    ASSETS_DOWNLOAD_TEMPLETE: "Download Template",
    ASSETS_UPLOAD_DATA: "Upload Data",
    ASSETS_SERIAL_ID: "Serial Id",
    ASSETS_NAME: "Asset Name",
    ASSETS_TYPE: "Asset Type",
    ASSETS_PURCHASE_TYPE: "Purchase Type",
    ASSETS_REMARK: "Remark",
    ASSETS_DESCRIPTION: "Description",
    ASSETS_ALLOCATION_DATE: "Allocation Date",
    ASSETS_UPLOAD_EXCEL: "apiapi",
    ASSETS_DOWNLOAD_TEMPLETE_NAME: "some value",

    // Department
    DEPARTMENT_TITLE: "Department",
    DEPARTMENT_ADD: "Add Department",
    DEPARTMENT_UDATE: "Update Department",
    DEPARTMENT_CODE: "Code",
    DEPARTMENT_NAME: "Department Name",
    DEPARTMENT_REMARK: "Remarks (If Any)",
    DEPARTMENT_STATUS: "Status",
    DEPARTMENT_ACTION: "Action",

    // Designation
    DESIGNATION_TITLE: "Designation",
    DESIGNATION_ADD: "Add Designation",
    DESIGNATION_UDATE: "Update Designation",
    DESIGNATION_CODE: "Code",
    DESIGNATION_NAME: "Designation Name",
    DESIGNATION_DESCRIPTION: "Description",
    DESIGNATION_STATUS: "Status",
    DESIGNATION_ACTION: "Action",

    // Assets Mapping
    AASETS_MAPPING_TITLE: "Assets Mapping",
    AASETS_MAPPING_ADD: "Add Assets Mapping",
    AASETS_MAPPING_UDATE: "Update Assets Mapping",
    AASETS_MAPPING_EMPLOYEE: "Employee",
    AASETS_MAPPING_SELECT_EMPLOYEE: "Select Employee",
    AASETS_MAPPING_ASSETS: "Assets",
    AASETS_MAPPING_STATUS: "Status",
    AASETS_MAPPING_ACTION: "Action",


    // About us
    // ABOUT_US: "<div><h1>About us</h1></div><p>Certainty is a Data Analytics company with a focus on solving client's end-to-end analytical problems. We are a team of innovative Data Scientists and Data Engineers who provide strategic consulting, thought leadership, and co-creation of revolutionary solutions.</p><p>The company was incorporated in the year 2017, and the foundation was laid by Madan Agrawal and Tarun Sinhal. Their sharp tactical and people management skills and problem-solving abilities are the cornerstones for leading the company on the right path. </p><p>The strategic approach of the founders builds an open and flexible work culture. We have a diverse pool of talented employees, and as said, that the success of the company lays in the hand of the employees working with them. </p><p>We believe that Company's growth is directly linked with Employees' growth and we provide necessary development opportunities and training platforms to help employees enhance their skills. </p><p>For more details visit <a href=\"https://certaintyinfotech.com\" target=\"_blank\">www.certaintyinfotech.com </a></p><a href=\"https://certaintyinfotech.com\" target=\"_blank\"></a>",

    // Orgnization tree
    ORGNIZATION_TREE_TITLE: "Organization Tree",

    // HR Policy
    HR_POLICY_TITLE: "HR Policy's",
    HR_POLICY_LABEL_TITLE: "Title",
    HR_POLICY_ADD: "Add HR Policy",
    HR_POLICY_UPDATE: "Update HR Policy",
    HR_POLICY_DATE: "Date",
    HR_POLICY_PDF_UPLOAD: "PDF Upload",
    HR_POLICY_REMARK: "Remark",
    HR_POLICY_PDF_FOR_VIEW: "PDF for View",
    HR_POLICY_ACTION: "Action",
    HR_POLICY_ALL_RECORED: "All Recored",
    HR_POLICY_LATEST_RECORED: "Latest Recored",
    HR_POLICY_SELECT: "Select Policy",

    // Holiday list
    HOLIDAY_LIST_TITLE: "Holiday List",
    HOLIDAY_LIST_ADD: "Add Holiday List",
    HOLIDAY_LIST_UPDATE: "Update Holiday List",
    HOLIDAY_LIST_OCCASION: "Occasion",
    HOLIDAY_LIST_DATE: "Date",
    HOLIDAY_LIST_COMMENTS: "Comments",
    HOLIDAY_LIST_SELECT_YEAR: "Select Year",
    HOLIDAY_LIST_DAY: "Day",
    HOLIDAY_LIST_ACTION: "Action",


    // Leaves Balance
    LEAVES_BALANCE_TITLE: "Leaves Balance",
    LEAVES_BALANCE_ADD: "Add Leaves Balance",
    LEAVES_BALANCE_UPDATE: "Update Leaves Balance",
    LEAVES_BALANCE_YEAR: "Year",
    LEAVES_BALANCE_EMPLOYEE: "Employee",
    LEAVES_BALANCE_EMPLOYEE_NAME: "Employee Name",
    LEAVES_BALANCE_START_DATE: "Start Date",
    LEAVES_BALANCE_CURRENT_DATE: "Current Date",
    LEAVES_BALANCE_TOTAL_EARNED_LEAVES: "Total Earned Leaves",
    LEAVES_BALANCE_TOTAL_CASUAL_LEAVES: "Total Casual Leaves",
    LEAVES_BALANCE_ELIGIBLE_SICK_LEAVES: "Eligible Sick Leaves",
    LEAVES_BALANCE_ELIGIBLE_EARNED_LEAVES: "Eligible Earned Leaves",
    LEAVES_BALANCE_CARRY_FORWORD_LAST_YEAR: "Carry Forward EL",
    LEAVES_BALANCE_LEAVES_WITHOUT_PAY: "Leave Without Pay",
    LEAVES_BALANCE_LWP_COMMENTS: "LWP Comments",
    LEAVES_BALANCE_EL_TAKEN_IN_CURRENT_YEAR: "EL Taken in current year",
    LEAVES_BALANCE_EL_COMMENTS: "EL Comments",
    LEAVES_BALANCE_SL_CL_TAKEN_IN_CURRENT_YEAR: "SL/CL Taken in current year",
    LEAVES_BALANCE_SL_CL_COMMENTS: "SL/CL Comments",
    LEAVES_BALANCE_EL_ENCASHED: "EL Encashed",
    LEAVES_BALANCE_EL_BALANCE: "EL Balance",
    LEAVES_BALANCE_SL_CL_BALANCE: "SL/CL Balance",
    LEAVES_BALANCE_ALL_RECORD: "ALL Record",
    LEAVES_BALANCE_LATEST_RECORD: "Latest Record",
    LEAVES_BALANCE_SELECT_EMPLOYEE_CODE: "Select Employee Code",
    LEAVES_BALANCE_TOTAL_LEAVES: "Total Leaves",
    LEAVES_BALANCE_ELIGIBLE_LEAVES: "Eligible Leaves",
    LEAVES_BALANCE_CURRENT_YEAR_LEAVES_OR_COMMENTS: "Current Year Leaves",
    LEAVES_BALANCE_LEAVES: "Balance Leaves",
    LEAVES_BALANCE_STATUS: "Status",
    LEAVES_BALANCE_ACTION: "Action",
    LEAVES_BALANCE_EARNED: "Earned :",
    LEAVES_BALANCE_CASUSL: "Casual :",
    LEAVES_BALANCE_SICK: "Sick :",
    LEAVES_BALANCE_COMMENT: "Comment :",
    LEAVES_BALANCE_LWP: "LWP :",
    LEAVES_BALANCE_EL: "EL :",
    LEAVES_BALANCE_SL: "SL :",
    LEAVES_BALANCE_ENCASHED: "Encashed :",
    LEAVES_BALANCE_SL_CL: "SL/CL :",
    LEAVE_BALANCE_SELECT_YEAR: "--Select Year--",
    LEAVE_BALANCE_SELECT_EMPLOYEE: "--Select Employee--",
    LEAVES_BASIC_DETAILS: "Basic Details",
    LEAVES_EL: "Earned Leaves",
    LEAVES_VERSION_HISTORY: "Version History",
    LEAVES_ID: "Id",

    // Opening
    OPENING_TITLE: "Opening",
    OPENING_ADD: "Add Opening",
    OPENING_UPDATE: "Update Opening",
    OPENING_COPY: "Copy Opening",
    OPENING_HIRING: "Hiring Type",
    OPENING_HIRING_TYPE: "Type",
    OPENING_SELECT_HIRING: "--Select Value--",
    OPENING_JOB_PROFILE: "Job-Profile",
    OPENING_PROFILE: "Profile",
    OPENING_EXPERIANCE: "Experience",
    OPENING_STATUS: "Status",
    OPENING_SELECT_STATUS: "--Select Status--",
    OPENING_NUMBER_OF_OPENINGS: "Number of Openings",
    OPENING_OPENINGS: "Openings",
    OPENING_WORK_LOCATION: "Work Location",
    OPENING_LOCATION: "Location",
    OPENING_ADDITIONAL_INFORMATION: "Additional Information",
    OPENING_JOB_DESCRIPTION_DOCUMENT: "Job Description Document",
    OPENING_FILTER_TYPE: "--Filter Type--",
    OPENING_DOCUMENT: "File",
    OPENING_ACTION: "Action",
    OPENING_CANDIDATE: "Candidates",
    OPENING_CODE: "Code",
    OPENING_REMAINING_OPENING: "Remaining Openings",

    // Candidate
    CANDIDATE_TITLE: "Candidate",
    CANDIDATE_ADD: "Add Candidate",
    CANDIDATE_UPDATE: "Update Candidate",
    CANDIDATE_COPY: "Copy Candidate",
    CANDIDATE_SELECT_VALUE: "Select",
    CANDIDATE_TYPE: "Type",
    CANDIDATE_ALL: "All",
    CANDIDATE_LATERAL: "Lateral",
    CANDIDATE_FRESHER: "Fresher",
    CANDIDATE_PROFILE: "Profile",
    CANDIDATE_NAME: "Candidate Name",
    CANDIDATE_EMAIL_ID: "Email Id",
    CANDIDATE_CONTACT_NUMBER: "Contact Number",
    CANDIDATE_EXPERIANCE: "Experiance",
    CANDIDATE_EXPERIANCE_TILL_CURRENT_DATE: "Total Experience (Yrs.)",
    CANDIDATE_CURRENT_LOCATION: "Current Location",
    CANDIDATE_TECHNOLOGIES_OR_SKILL_SET: "Technologies/Skill-set",
    CANDIDATE_COLLEGE: "PG - College",
    CANDIDATE_GRADUATION: "UG - college",
    CANDIDATE_GRADUATION_YEAR: "PG - Graduation Year",
    CANDIDATE_STREAM: "Stream",
    CANDIDATE_TENTH: "10th %",
    CANDIDATE_TWELTH: "12th %",
    CANDIDATE_GRAD_CGPA: "Grad CGPA",
    CANDIDATE_PG_CGPA: "PG CGPA",
    CANDIDATE_READY_TO_RELOCATE: "Ready to Relocate to Indore",
    CANDIDATE_HIRING_MODE: "Hiring Mode",
    CANDIDATE_ROUND_ONE: "Round - 01",
    CANDIDATE_ROUND_ONE_RESULT: "Round - 01 Result",
    CANDIDATE_ROUND_TWO: "Round - 02",
    CANDIDATE_ROUND_TWO_RESULT: "Round - 02 Result",
    CANDIDATE_REMARK: "Remark",
    CANDIDATE_FINAL_STATUS: "Final Status",
    CANDIDATE_RESUME_UPLOAD: "Resume Upload",
    CANDIDATE_OFFERED: "Offered:",
    CANDIDATE_YES: "Yes",
    CANDIDATE_NO: "No",
    CANDIDATE_AMOUNT: "Amount",
    CANDIDATE_REASON: "Reason",
    CANDIDATE_EXPECTED_CTC: "Expected CTC",
    CANDIDATE_NOTICE_PERIOD: "Notice Period",
    CANDIDATE_CURRENT_OR_LAST_COMPCANDIDATE_EXPERIANCEANY_NAME: "Current/Last Company Name",
    CANDIDATE_CURRENT_DESIGNATION_OR_ROLE: "Current Designation/Role",
    CANDIDATE_CURRENT_CTC: "Current CTC",
    CANDIDATE_ACTION: "Action",
    CANDIDATE_DOC: "Doc",
    CANDIDATE_CODE: "Code",
    CANDIDATE_APPLICATION_DATE: "Application Date",
    CANDIDATE_CURRENT_DATE: "Current Date",
    CANDIDATE_EXPERIANCE_ON_CURRENT_DATE: "Experience on Current Date",
    CANDIDATE_ROUND_THREE: "Round - 03(If Any)",
    CANDIDATE_FINAL_ROUND: "Final Status",
    CANDIDATE_ACCEPTED: "Accepted:",
    CANDIDATE_JOINING_DATE: "Joining Date",
    CANDIDATE_SEARCH_TAG: "Search Tag",
    CANDIDATE_MODIFY_STATUS: "Modify Status",

    // Employee List
    EMAIL: "Email",
    REPORTING: "Reporting",


    // Employee Add
    EMPLOYEE_TITLE: "Employee Directory",
    EMPLOYEE_ADD: "Add Employee",
    EMPLOYEE_COPY_ADDRESS_TEXT: "Copy address",
    EMPLOYEE_UNCOPY_ADDRESS_TEXT: "Reset address",

    // Employee Home
    EMPLOYEE_FULL_NAME: "Full Name",
    EMPLOYEE_PERSONAL_EMAIL_ID: "Personal email ID",
    EMPLOYEE_MOBILE_NUMBER: "Mobile no.",
    EMPLOYEE_GRADE: "Grade",
    EMPLOYEE_DOB_ACTUAL: "DOB-Actual",
    EMPLOYEE_DESIGNATION: "Designation",
    EMPLOYEE_OFFICIAL_EMAIL: "Official Email",
    EMPLOYEE_DATE_OF_JOINING: "Date of Joining",
    EMPLOYEE_ALTERNATE_NUMBER: "Alternate Number",
    EMPLOYEE_BANK_ACCOUNT_NUMBER: "Bank Account Number",
    EMPLOYEE_MARRIAGE_ANNIVERSARY: "Marriage Anniversary",
    EMPLOYEE_DOB_DOCUMENTED: "DOB-documented",
    EMPLOYEE_LAST_WORKING_DAY: "Last Working Day",
    EMPLOYEE_IFSC_CODE: "IFSC code",
    EMPLOYEE_MICROSOFT_EMAIL: "Microsoft Email",
    EMPLOYEE_GENDER: "Gender:",
    EMPLOYEE_MALE: "Male",
    EMPLOYEE_FEMALE: "Female",
    EMPLOYEE_AADHAR_NUMBER: "Aadhar Number",
    EMPLOYEE_MANAGER: "Reporting Manager",
    EMPLOYEE_PRIMARY_MANAGER: "Primary Manager",
    EMPLOYEE_TEMPORARY_ADDRESS: "Temporary Address",
    EMPLOYEE_PERMANENT_ADDRESS: "Permanent Address",
    EMPLOYEE_PAN_NUMBER: "PAN Number",
    EMPLOYEE_RESIGNATION_DATE: "Resignation Date",
    EMPLOYEE_REASON_FOR_LEAVING: "Reason for Leaving",
    EMPLOYEE_BLOOD_GROUP: "Blood Group",
    EMPLOYEE_DEPARTMENT: "Department",
    PRIMARY_MANAGER: "Primary Manager",
    EXPERIENCE: "Experience",
    TOTAL_EXPERIENCE: "Total Experience",
    EMPLOYEE_EXIST: "Employee exist!",
    EMPLOYEE_WITH_SAME_CODE: "Employee with same code already exist.",
    EMPLOYEE_BLANK_PARAMETER: "Some mandatory field is blank please verify once.",
    EMPLOYEE_OK: "OK",
    MARRITAL_STATUS: "Marrital Status",
    MARRIED: "Married",
    UNMARRIED: "Unmarried",

    // Employee Update
    EMPLOYEE_STATUS: "Status",
    EMPLOYEE_REPORTING: "Reporting Manager",
    EMPLOYEE_PERSONAL: "Personal",
    EMPLOYEE_EMPLOYEMENT: "Empolyment",
    EMPLOYEE_DOCUMENTS: "Documents",
    EMPLOYEE_TIME: "Time",
    EMPLOYEE_PERSONAL_DETAILS: "PERSONAL DETAILS",
    EMPLOYEE_EMPLOYMENT_DETAILS: "EMPLOYMENT DETAILS",
    EMPLOYEE_CODE: "Employee Code",
    EMPLOYEE_DOCUMENTS_UPLOAD: "DOCUMENTS UPLOAD",
    EMPLOYEE_PERSONAL_DOCUMENTS: "Personal document",
    EMPLOYEE_PREVIOUS_ORGNIZATION_SALARY_SLIP: "Previous organization document",
    EMPLOYEE_DOCUMENTS_PROVIDED_BY_ORGNIZATION: "Documents provided by organization",
    EMPLOYEE_HIGH_SCHOOL_MARKSHEET: "High School Marksheet",
    EMPLOYEE_HIGH_SECONDARY_MARKSHEET: "High Secondary Marksheet",
    EMPLOYEE_PAN_CARD: "PAN Card",
    EMPLOYEE_RELIEVING_CERTIFICATE: "Relieving Certificate",
    EMPLOYEE_PG_DOCUMENT: "PG Document",
    EMPLOYEE_UG_DOCUMENT: "UG Documnt",
    EMPLOYEE_OTHER_DOCUMENT: "Other Document",
    EMPLOYEE_BANK_STATEMENT: "Bank Statement",
    EMPLOYEE_PERSONAL_ID: "Personal Id",
    EMPLOYEE_SUBMIT: "Submit",
    EMPLOYEE_ADD_MULTIPLE_SALARY_SLIP: "Add Multiple Documents",
    EMPLOYEE_SERIAL_ID: "Serial Id",
    EMPLOYEE_SALARY_SLIP: "Salary Slip",
    EMPLOYEE_ACTION: "Action",
    EMPLOYEE_VIEW: "View",
    EMPLOYEE_JOINING_LETTER: "Joining Latter",
    EMPLOYEE_OFFER_LETTER: "offer Latter",
    EMPLOYEE_FNF_SALARY_SLIP: "FNF salary slip",
    EMPLOYEE_NDA: "NDA",
    EMPLOYEE_EXPERIANCE_CERTIFICATE: "Experience Certificate",
    EMPLOYEE_PREVIOUS_WORK: "Previous Work",
    EMPLOYEE_JOINING_WORK: "Joining Work",
    EMPLOYEE_ASSETS_ALLOTED: "Assets Alloted",
    EMPLOYEE_DOCUMENT: "Document",
    EMPLOYEE_DOCUMENT_NAME: "Document name",
    EMPLOYEE_DOCUMENT_COMMENT: "Comment",
    EMPLOYEE_DOCUMENT_SERIAL: "Sr. No",
    EMPLOYEE_DOCUMENT_CHOOSE_FILE: "Choose File",

    //Leaves Request
    LEAVES_REQUEST_TITLE: "Leave Request",
    LEAVES_REQUEST_ADD: "Add Leave Request",
    LEAVES_REQUEST_FOR: "Leave Request for",
    LEAVES_REQUEST_DAYS: "days",
    LEAVES_REQUEST_FROM_DATE: "From Date",
    LEAVES_REQUEST_TO_DATE: "To Date",
    LEAVES_REQUEST_SELECT_AVAILABLE_LEAVE: "Select available leave type",
    LEAVES_REQUEST_SELECT_LEAVE: "Select leave type",
    LEAVES_REQUEST_ONE: "One",
    LEAVES_REQUEST_TWO: "Two",
    LEAVES_REQUEST_THREE: "Three",
    LEAVES_REQUEST_NOTE: "NOTE",
    LEAVES_REQUEST_NOTIFY: "Notify",
    LEAVES_REQUEST_CANCEL: "Cancel",
    LEAVES_REQUEST_LEAVE: "Request leave",
    LEAVES_REQUEST_WEEK_OFF: "WeekOff",
    LEAVES: "Leave",
    LEAVES_REQUEST_HOLIDAY: "Holiday",

    //Payroll
    SALARY_TITLE:"Salary Payroll",
    ACTUAL_SALARY:"Actual Salary",
    TOTAL_INCOME:"Total Income",
    TOTAL_DEDUCTION:"Total Deduction",
    SALARY_PAID:"Salary Paid",
    MONTH_YEAR:"Month Year",
    NO_OF_CALENDER_DAYS:"No. of Calender Days",
    SALARY: "Salary",
    CALCULATION: "Calculation",
    FNF: "FNF",
    ADD: "Add",
    SERIAL: "Sr. No.",
    EMPLOYEE: "Employee",
    ANNUAL: "Annual",
    CTC: "CTC",
    MONTHLY: "Monthly",
    CREATED_ON: "Created On",
    CREATED_BY: "Created By",
    ACTION: "Action",
    SELECT_EMPLOYEE: "Select Employee",
    PF_OPTED: "PF Opted",
    YES: "Yes",
    NO: "No",
    PARTICULARS: "Particulars",
    BASIC_PAY: "Basic Pay",
    HOUSE_RENT_ALLOWANCE: "House Rent Allowance",
    MEDICAL_ALLOWANCE: "Medical Allowance",
    TRAVEL_ALLOWANCE: "Travel Allowance",
    SPECIAL_ALLOWANCE: "Special Allowance",
    GROSS_PAY: "Gross Pay",
    EMPLOYER_CONTRIBUTION: "Employer Contribution",
    PF_IF_OPTED: "PF(If Opted)",
    PTAX: "P.Tax",
    GRATUITY: "Gratuity",
    TDS: "TDS",
    AS_APPLICABLE: "IT(As applicable)",
    AS_PER_APPLICABILITY: "As per applicability",
    EARNINGS: "Earnings",
    DEDUCTIONS: "Deductions",
    TOTAL: "Total",
    NET_PAY: "Net Pay",
    EMPLOYEE_NAME: "Employee Name",
    TOTAL_AMOUNT_FOR_FNF: "Total Amount for F&F Settlement",
    EL_BALANCE: "Earned leave Balance",
    WORKED_DAYS: "Current month - calender days worked",
    PREVIOUS_SALARY: "Previous salary arrears",
    ADVANCE_SALARY: "Advance salaries given",
    REMARKS: "Remarks",
    FIELDS: "Fields",
    DETAILS: "Details",
    NAME: "Name",
    DATE_OF_JOINIG: "Date Of Joining",
    LAST_DAY_OF_WORKING: "Last day of working",
    GROSS_SALARY: "Gross salary (at time of leaving)",
    BASIC_SALARY: "Basic Salary (at time of leaving)",
    LEAVE_ENCASHMENT: "Leave Encashment",
    PENDING_SALARY: "Pending salary for current month",
    NET_SALARY: "Net salary pending",
    PROFESSION_TAX: "Profession Tax",
    PF_EMPLOYEE_CONTRI: "PF Employee contri",
    PF_EMPLOYER_CONTRI: "PF Employer contri",
    WORK: "Work",
    PAY: "Pay",
    ALLOWANCE: "Allowance",
    EXTRA: "Extra",
    DIDUCTION: "Diduction",
    CREATOR: "CREATOR",
    STATUS:"Status",
    MONTHYAER:"Month-Year",
    WORKING_DAYS:"Working Days",
    P_LEAVES:"Laves",
    LWP:"LWP",
    PAYABLE_DAYS:"Payable Days",
    ACTUAL_PAY:"Actual Pay",
    TOTAL_PAY:"Total Paid",
    TOTAL_SALARY_STATUS:"Total Salary Status",
    PER_DAY_SALARY:"Per Day Salary",
    HRA:"HRA",
    INCENTIVES:"Incentives",
    EXTRA_PAY:"Extra Payment",
    PF:"PF",
    OTHER_DEDUCTION:"Other Deduction",
    MONTH:"Month",
    YEAR:"Year",
    JANUARY:"January",
    FEBRUARY:"February",
    MARCH:"March",
    APRIL:"April",
    MAY:"May",
    JUNE:"June",
    JULY:"July",
    AUGUST:"August",
    SEPTEMBER:"September",
    OCTOBER:"October",
    NOVEMBER:"November",
    DECEMBER:"December",
    FNF_SALARY_TITLE:"FNF Salary",
    TOTAL_WORKING_DAYS:"Total Working Days",
    TOTAL_LEAVE_TAKEN:"Total Leave Taken",
    EXTRA_PAY_EXCLUSIVE:"Extra Pay Exclusive",
    DESIGNATION:"Designation",
    NON_WORKING_DAYS:"Non working days - deduction/LWP",
    TO_PAID:"To Paid",
    SPAY:"PAY",
    DEDUCTION:"Deduction",
    ADDITIONS:"Additions",
    EXTRA_PAY_EX:"Extra Payments Exclusive from Salary",
    OWNER:"Owner",
    LEAVES_P:"Leaves",
    PTAX_VALUE2:"166 and 167 if last month",
    PTAX_VALUE3:"208 and 212 if last month",
    PF_EMPLOYEE:"PF Employee",
    PF_EMPLOYER:"PF Employer",
    SALARY_WITH_VARIABLE:"Salary With Variable Calculation",
    VARIABLE_PAY:"Variable Pay",
    GROSS_TOTAL:"Gross Total"
}